### ISSUE TITLE
Supervisors on-boarding documentation

### ISSUE THREAD

**Issue by jurra** [delftopenhardware/for-org-board#15]
# Procedure to onboard supervisors

## Clear messages to communicate
- What are we have been doing.

- Explain how it works
    - Submit assignments, we publish them and promote them online
    - Describe the assignment in such a way that is clear for potential students, developers.
    - Explain different work-packages expected by the program
    - Discuss considerations for those working on multiple projects
    - Discuss requirements on assignment publishing, even when a researcher has already a student

- Procedure
    - Follow the guide to submit assignments
    - Submit separate assignments (Bare in mind that a project can be composed of multiple assignments from our perspective, but also, multiple projects could be also each an assginemt) We recommend to break down a project into several assignments when its very complex and requires the contribution of different individuals developing different workpackages. 

## Issues, To dos, Urgents
- Update the documentation with Jerry's assignment (Jose)
- How does the finance works (Santosh) We are setting the process with Finance, most likely you recieve all the funding in advance. This is our expectation.
- Create the form to submit assignments (Jose)
- Explain the context of DEMO and documentation (Jose)
- Procedure to onboard specifically developers. Our recommendation is to follow an onboarding meeting, then the developer should follow the open hardware materials and come with questions to the support team, on how to address a particular issue. We would appreciate if the supervisor also encourages the developer/student to take seriously the material. It is mandatory to have midterm presentation following a simple protocol, and also a final presentation. (Examples will be provided to them)

**Comment by jurra** [comment]
Case 1: OHSF-SU-24-04#6
Wants to have more than 3 hardware design projects, we need to find out how projects many exactly.
Wants to cover material costs for the development of Master Thesis.
Question marks?
- How many Master Thesis?
- Is there a master thesis associated to one single project, or a project can be composed of several master thesis contributing to a different aspect or work package?
- Do you expect the master student to develop everything by themselves, or do you need technical support of some kind?
- Duration will be more than 12 months, does this apply for all projects or only one, or is it because you are placing the projects in different schedules?

**Comment by santoshilam** [comment]
# Meeting for OHSF-SU-24-04#06 

Attendees: Przemysław Pawełczak, Vivian Dsouza, Jose Urra, Santosh Ilamparuthi 
Time: 27/03/2024; 14:00

The members of the team are already set, it will be Przemyslaw, Vivian and a Masters student
Only material costs. 
This instance will be the development of the battery free version of the sensor. Subsequent version would probably dealt with as new projects. 

The assignments will be held closed until the paper based on this work is accepted in the publishing.
